### ISSUE TITLE
Trained_Tagger.pkl

### ISSUE THREAD

**Issue by Mustyy** [alexandercrosson/nlp#1]
Hey Alexander

Hope all is well

When I run the script I keep getting an error

IOError: [Errno 2] No such file or directory: 'trained_tagger.pkl'

Any idea why this happens?
and also I have my own corpus I want to try this script on
Do I only need to change the URL path?

Looking forward to your reply
Thank you again

**Comment by acrosson** [comment]
set trained_tagger=False 

ex.
trigram_tagger = trained_tagger(existing=False)

it will create the trainer and persist it to disk via pickle. after that you can set it to False so you don't have to create it every time you run the script.

**Comment by Mustyy** [comment]
Thank you 
That makes it work
One more thing
I fed it my own corpus of sentences with company names 
However all my subjects = Company
eg. {'action': u'leading', 'phrase': [(u'company', u'NN'), (u'founded', u'VBD'), (u'leading', u'VBG'), (u'provider', 'NN')], 'object': u'provider', 'subject': u'company'}

Is there a way for the subject to identify the proper company name as an entity?
