### ISSUE TITLE
Load corpus data used to train the TF-IDF Transformer

### ISSUE THREAD

**Issue by Mustyy** [alexandercrosson/nlp#2]
Hey Alexander
Hope all is well

Quick question, I downloaded the WikiCorpus but how do i generate a 
data = pickle.load(open(‘data.pkl’, ‘rb’))?

**Comment by acrosson** [comment]
Hi @Mustyy 

Load the wiki corpus into an array of articles.
Then just write it to a pickle file. data.pkl is just a list of documents.

Here's an example:
data = [load_data('./data/blogs/', file_name) for file_name in file_names]
pickle.dump(data, open('data.pkl', 'wb'))

**Comment by Mustyy** [comment]
Hey Alexander
Thanks for the promt reply

The file i uploaded to my server is in tgz format
I'm thinking if there is a quick way to dump all of it into a pickle file

**Comment by acrosson** [comment]
You just need to load all the documents into memory. Use the python **with open()** function, and load each document into a list.

**Comment by Mustyy** [comment]
@alexandercrosson 
Hey
Hope all is well

I'm still struggling with writing the files into a pkl format
I unzipped the original file and loaded all the separate files into a directory 

Any simple way of doing this quickly would be appreciated
Thank you

**Comment by Mustyy** [comment]
@alexandercrosson 

This is what I did

import pickle
import os

for filename in os.listdir('/home/ubuntu/nlp/raw.en'):
   with open('/home/ubuntu/nlp/raw.en/' + filename, 'r') as data_file:
        pickle.dump(data_file, open('data.pkl', 'wb'))

error : TypeError: can't pickle file objects
